/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.pycom.ActuatorType;
import xtext.pycom.PycomPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Actuator Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ActuatorTypeImpl extends ModuleTypeImpl implements ActuatorType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActuatorTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PycomPackage.Literals.ACTUATOR_TYPE;
  }

} //ActuatorTypeImpl
