/**
 * generated by Xtext 2.16.0
 */
package xtext.validation;

import xtext.validation.AbstractPycomValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PycomValidator extends AbstractPycomValidator {
}
