/**
 * generated by Xtext 2.16.0
 */
package xtext.ui.contentassist;

import xtext.ui.contentassist.AbstractPycomProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PycomProposalProvider extends AbstractPycomProposalProvider {
}
