/**
 * generated by Xtext 2.16.0
 */
package xtext;

import xtext.AbstractPycomRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PycomRuntimeModule extends AbstractPycomRuntimeModule {
}
