/*
 * generated by Xtext 2.16.0
 */
package xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import xtext.PycomRuntimeModule
import xtext.PycomStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PycomIdeSetup extends PycomStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PycomRuntimeModule, new PycomIdeModule))
	}
	
}
