/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Boolean#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends LogicExp
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see xtext.pycom.PycomPackage#getBoolean_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link xtext.pycom.Boolean#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Boolean
