/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.ComparisonExp#getLeft <em>Left</em>}</li>
 *   <li>{@link xtext.pycom.ComparisonExp#getOp <em>Op</em>}</li>
 *   <li>{@link xtext.pycom.ComparisonExp#getRigth <em>Rigth</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getComparisonExp()
 * @model
 * @generated
 */
public interface ComparisonExp extends LogicExp
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expression)
   * @see xtext.pycom.PycomPackage#getComparisonExp_Left()
   * @model containment="true"
   * @generated
   */
  Expression getLeft();

  /**
   * Sets the value of the '{@link xtext.pycom.ComparisonExp#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see xtext.pycom.PycomPackage#getComparisonExp_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link xtext.pycom.ComparisonExp#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Rigth</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rigth</em>' containment reference.
   * @see #setRigth(Expression)
   * @see xtext.pycom.PycomPackage#getComparisonExp_Rigth()
   * @model containment="true"
   * @generated
   */
  Expression getRigth();

  /**
   * Sets the value of the '{@link xtext.pycom.ComparisonExp#getRigth <em>Rigth</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rigth</em>' containment reference.
   * @see #getRigth()
   * @generated
   */
  void setRigth(Expression value);

} // ComparisonExp
