/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.pycom.PycomPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
