/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.LogicExp#getBoolVal <em>Bool Val</em>}</li>
 *   <li>{@link xtext.pycom.LogicExp#getCompExp <em>Comp Exp</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getLogicExp()
 * @model
 * @generated
 */
public interface LogicExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Bool Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Val</em>' containment reference.
   * @see #setBoolVal(xtext.pycom.Boolean)
   * @see xtext.pycom.PycomPackage#getLogicExp_BoolVal()
   * @model containment="true"
   * @generated
   */
  xtext.pycom.Boolean getBoolVal();

  /**
   * Sets the value of the '{@link xtext.pycom.LogicExp#getBoolVal <em>Bool Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Val</em>' containment reference.
   * @see #getBoolVal()
   * @generated
   */
  void setBoolVal(xtext.pycom.Boolean value);

  /**
   * Returns the value of the '<em><b>Comp Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp Exp</em>' containment reference.
   * @see #setCompExp(ComparisonExp)
   * @see xtext.pycom.PycomPackage#getLogicExp_CompExp()
   * @model containment="true"
   * @generated
   */
  ComparisonExp getCompExp();

  /**
   * Sets the value of the '{@link xtext.pycom.LogicExp#getCompExp <em>Comp Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp Exp</em>' containment reference.
   * @see #getCompExp()
   * @generated
   */
  void setCompExp(ComparisonExp value);

} // LogicExp
