/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.pycom.PycomFactory
 * @model kind="package"
 * @generated
 */
public interface PycomPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pycom";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Pycom.xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pycom";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PycomPackage eINSTANCE = xtext.pycom.impl.PycomPackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.pycom.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.SystemImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Boards</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__BOARDS = 0;

  /**
   * The feature id for the '<em><b>Servers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SERVERS = 1;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ServerImpl <em>Server</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ServerImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getServer()
   * @generated
   */
  int SERVER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__NAME = 0;

  /**
   * The feature id for the '<em><b>Conn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__CONN = 1;

  /**
   * The feature id for the '<em><b>Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__EXPS = 2;

  /**
   * The number of structural features of the '<em>Server</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ConnectionImpl <em>Connection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ConnectionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getConnection()
   * @generated
   */
  int CONNECTION = 2;

  /**
   * The feature id for the '<em><b>Ip Adr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__IP_ADR = 0;

  /**
   * The feature id for the '<em><b>Website</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__WEBSITE = 1;

  /**
   * The feature id for the '<em><b>Portnumber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__PORTNUMBER = 2;

  /**
   * The number of structural features of the '<em>Connection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.BoardImpl <em>Board</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.BoardImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getBoard()
   * @generated
   */
  int BOARD = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__NAME = 0;

  /**
   * The feature id for the '<em><b>Board Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__BOARD_MEMBERS = 1;

  /**
   * The number of structural features of the '<em>Board</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.BoardMemberImpl <em>Board Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.BoardMemberImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getBoardMember()
   * @generated
   */
  int BOARD_MEMBER = 4;

  /**
   * The number of structural features of the '<em>Board Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_MEMBER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ExpMemberImpl <em>Exp Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ExpMemberImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getExpMember()
   * @generated
   */
  int EXP_MEMBER = 6;

  /**
   * The number of structural features of the '<em>Exp Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MEMBER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ConditionalActionImpl <em>Conditional Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ConditionalActionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getConditionalAction()
   * @generated
   */
  int CONDITIONAL_ACTION = 5;

  /**
   * The number of structural features of the '<em>Conditional Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_ACTION_FEATURE_COUNT = EXP_MEMBER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.SensorImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 7;

  /**
   * The feature id for the '<em><b>Sensor Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__SENSOR_TYPES = BOARD_MEMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = BOARD_MEMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ActuatorImpl <em>Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ActuatorImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getActuator()
   * @generated
   */
  int ACTUATOR = 8;

  /**
   * The feature id for the '<em><b>Actuator Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__ACTUATOR_TYPES = BOARD_MEMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_FEATURE_COUNT = BOARD_MEMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ActuatorTypeImpl <em>Actuator Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ActuatorTypeImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getActuatorType()
   * @generated
   */
  int ACTUATOR_TYPE = 9;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_TYPE__TYPE_NAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_TYPE__NAME = 1;

  /**
   * The feature id for the '<em><b>Pins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_TYPE__PINS = 2;

  /**
   * The number of structural features of the '<em>Actuator Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.SensorTypeImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getSensorType()
   * @generated
   */
  int SENSOR_TYPE = 10;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE__TYPE_NAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE__NAME = 1;

  /**
   * The feature id for the '<em><b>Pins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE__PINS = 2;

  /**
   * The number of structural features of the '<em>Sensor Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.PinImpl <em>Pin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.PinImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getPin()
   * @generated
   */
  int PIN = 11;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN__POWER = 0;

  /**
   * The feature id for the '<em><b>Input</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN__INPUT = 1;

  /**
   * The number of structural features of the '<em>Pin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ConditionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 12;

  /**
   * The feature id for the '<em><b>Exp Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__EXP_MEMBERS = CONDITIONAL_ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = CONDITIONAL_ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.LogicExpImpl <em>Logic Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.LogicExpImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getLogicExp()
   * @generated
   */
  int LOGIC_EXP = 13;

  /**
   * The feature id for the '<em><b>Exp Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__EXP_MEMBERS = CONDITION__EXP_MEMBERS;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__CONDITION = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Logic Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.BooleanImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 14;

  /**
   * The feature id for the '<em><b>Exp Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__EXP_MEMBERS = LOGIC_EXP__EXP_MEMBERS;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__CONDITION = LOGIC_EXP__CONDITION;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__VALUE = LOGIC_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = LOGIC_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ComparisonExpImpl <em>Comparison Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ComparisonExpImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getComparisonExp()
   * @generated
   */
  int COMPARISON_EXP = 15;

  /**
   * The feature id for the '<em><b>Exp Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__EXP_MEMBERS = LOGIC_EXP__EXP_MEMBERS;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__CONDITION = LOGIC_EXP__CONDITION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__LEFT = LOGIC_EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__OP = LOGIC_EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__RIGTH = LOGIC_EXP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP_FEATURE_COUNT = LOGIC_EXP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ExpressionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 16;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.FunctionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 17;

  /**
   * The feature id for the '<em><b>Board</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__BOARD = EXP_MEMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = EXP_MEMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ActuatorFunctionImpl <em>Actuator Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ActuatorFunctionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getActuatorFunction()
   * @generated
   */
  int ACTUATOR_FUNCTION = 18;

  /**
   * The feature id for the '<em><b>Board</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_FUNCTION__BOARD = FUNCTION__BOARD;

  /**
   * The feature id for the '<em><b>Actuator Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_FUNCTION__ACTUATOR_TYPE = FUNCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Actuator Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_FUNCTION_FEATURE_COUNT = FUNCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.SensorFunctionImpl <em>Sensor Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.SensorFunctionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getSensorFunction()
   * @generated
   */
  int SENSOR_FUNCTION = 19;

  /**
   * The feature id for the '<em><b>Board</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FUNCTION__BOARD = FUNCTION__BOARD;

  /**
   * The feature id for the '<em><b>Sensor Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FUNCTION__SENSOR_TYPE = FUNCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sensor Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FUNCTION_FEATURE_COUNT = FUNCTION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link xtext.pycom.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see xtext.pycom.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.System#getBoards <em>Boards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Boards</em>'.
   * @see xtext.pycom.System#getBoards()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Boards();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.System#getServers <em>Servers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servers</em>'.
   * @see xtext.pycom.System#getServers()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Servers();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Server <em>Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server</em>'.
   * @see xtext.pycom.Server
   * @generated
   */
  EClass getServer();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Server#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.Server#getName()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_Name();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Server#getConn <em>Conn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conn</em>'.
   * @see xtext.pycom.Server#getConn()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Conn();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Server#getExps <em>Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exps</em>'.
   * @see xtext.pycom.Server#getExps()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Exps();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Connection <em>Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection</em>'.
   * @see xtext.pycom.Connection
   * @generated
   */
  EClass getConnection();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Connection#getIpAdr <em>Ip Adr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip Adr</em>'.
   * @see xtext.pycom.Connection#getIpAdr()
   * @see #getConnection()
   * @generated
   */
  EAttribute getConnection_IpAdr();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Connection#getWebsite <em>Website</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Website</em>'.
   * @see xtext.pycom.Connection#getWebsite()
   * @see #getConnection()
   * @generated
   */
  EAttribute getConnection_Website();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Connection#getPortnumber <em>Portnumber</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Portnumber</em>'.
   * @see xtext.pycom.Connection#getPortnumber()
   * @see #getConnection()
   * @generated
   */
  EAttribute getConnection_Portnumber();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Board <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Board</em>'.
   * @see xtext.pycom.Board
   * @generated
   */
  EClass getBoard();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Board#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.Board#getName()
   * @see #getBoard()
   * @generated
   */
  EAttribute getBoard_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Board#getBoardMembers <em>Board Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Board Members</em>'.
   * @see xtext.pycom.Board#getBoardMembers()
   * @see #getBoard()
   * @generated
   */
  EReference getBoard_BoardMembers();

  /**
   * Returns the meta object for class '{@link xtext.pycom.BoardMember <em>Board Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Board Member</em>'.
   * @see xtext.pycom.BoardMember
   * @generated
   */
  EClass getBoardMember();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ConditionalAction <em>Conditional Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional Action</em>'.
   * @see xtext.pycom.ConditionalAction
   * @generated
   */
  EClass getConditionalAction();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ExpMember <em>Exp Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Member</em>'.
   * @see xtext.pycom.ExpMember
   * @generated
   */
  EClass getExpMember();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see xtext.pycom.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Sensor#getSensorTypes <em>Sensor Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensor Types</em>'.
   * @see xtext.pycom.Sensor#getSensorTypes()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_SensorTypes();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Actuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator</em>'.
   * @see xtext.pycom.Actuator
   * @generated
   */
  EClass getActuator();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Actuator#getActuatorTypes <em>Actuator Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actuator Types</em>'.
   * @see xtext.pycom.Actuator#getActuatorTypes()
   * @see #getActuator()
   * @generated
   */
  EReference getActuator_ActuatorTypes();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ActuatorType <em>Actuator Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator Type</em>'.
   * @see xtext.pycom.ActuatorType
   * @generated
   */
  EClass getActuatorType();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ActuatorType#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Name</em>'.
   * @see xtext.pycom.ActuatorType#getTypeName()
   * @see #getActuatorType()
   * @generated
   */
  EAttribute getActuatorType_TypeName();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ActuatorType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.ActuatorType#getName()
   * @see #getActuatorType()
   * @generated
   */
  EAttribute getActuatorType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.ActuatorType#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pins</em>'.
   * @see xtext.pycom.ActuatorType#getPins()
   * @see #getActuatorType()
   * @generated
   */
  EReference getActuatorType_Pins();

  /**
   * Returns the meta object for class '{@link xtext.pycom.SensorType <em>Sensor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Type</em>'.
   * @see xtext.pycom.SensorType
   * @generated
   */
  EClass getSensorType();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.SensorType#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Name</em>'.
   * @see xtext.pycom.SensorType#getTypeName()
   * @see #getSensorType()
   * @generated
   */
  EAttribute getSensorType_TypeName();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.SensorType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.SensorType#getName()
   * @see #getSensorType()
   * @generated
   */
  EAttribute getSensorType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.SensorType#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pins</em>'.
   * @see xtext.pycom.SensorType#getPins()
   * @see #getSensorType()
   * @generated
   */
  EReference getSensorType_Pins();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Pin <em>Pin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pin</em>'.
   * @see xtext.pycom.Pin
   * @generated
   */
  EClass getPin();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Pin#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see xtext.pycom.Pin#getPower()
   * @see #getPin()
   * @generated
   */
  EAttribute getPin_Power();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Pin#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Input</em>'.
   * @see xtext.pycom.Pin#getInput()
   * @see #getPin()
   * @generated
   */
  EAttribute getPin_Input();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see xtext.pycom.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Condition#getExpMembers <em>Exp Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp Members</em>'.
   * @see xtext.pycom.Condition#getExpMembers()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_ExpMembers();

  /**
   * Returns the meta object for class '{@link xtext.pycom.LogicExp <em>Logic Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Exp</em>'.
   * @see xtext.pycom.LogicExp
   * @generated
   */
  EClass getLogicExp();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.LogicExp#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see xtext.pycom.LogicExp#getCondition()
   * @see #getLogicExp()
   * @generated
   */
  EReference getLogicExp_Condition();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see xtext.pycom.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Boolean#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see xtext.pycom.Boolean#getValue()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_Value();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ComparisonExp <em>Comparison Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison Exp</em>'.
   * @see xtext.pycom.ComparisonExp
   * @generated
   */
  EClass getComparisonExp();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.ComparisonExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see xtext.pycom.ComparisonExp#getLeft()
   * @see #getComparisonExp()
   * @generated
   */
  EReference getComparisonExp_Left();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ComparisonExp#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see xtext.pycom.ComparisonExp#getOp()
   * @see #getComparisonExp()
   * @generated
   */
  EAttribute getComparisonExp_Op();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.ComparisonExp#getRigth <em>Rigth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rigth</em>'.
   * @see xtext.pycom.ComparisonExp#getRigth()
   * @see #getComparisonExp()
   * @generated
   */
  EReference getComparisonExp_Rigth();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see xtext.pycom.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see xtext.pycom.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the reference '{@link xtext.pycom.Function#getBoard <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Board</em>'.
   * @see xtext.pycom.Function#getBoard()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Board();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ActuatorFunction <em>Actuator Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator Function</em>'.
   * @see xtext.pycom.ActuatorFunction
   * @generated
   */
  EClass getActuatorFunction();

  /**
   * Returns the meta object for the reference '{@link xtext.pycom.ActuatorFunction#getActuatorType <em>Actuator Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actuator Type</em>'.
   * @see xtext.pycom.ActuatorFunction#getActuatorType()
   * @see #getActuatorFunction()
   * @generated
   */
  EReference getActuatorFunction_ActuatorType();

  /**
   * Returns the meta object for class '{@link xtext.pycom.SensorFunction <em>Sensor Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Function</em>'.
   * @see xtext.pycom.SensorFunction
   * @generated
   */
  EClass getSensorFunction();

  /**
   * Returns the meta object for the reference '{@link xtext.pycom.SensorFunction#getSensorType <em>Sensor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor Type</em>'.
   * @see xtext.pycom.SensorFunction#getSensorType()
   * @see #getSensorFunction()
   * @generated
   */
  EReference getSensorFunction_SensorType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PycomFactory getPycomFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.pycom.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.SystemImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Boards</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__BOARDS = eINSTANCE.getSystem_Boards();

    /**
     * The meta object literal for the '<em><b>Servers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SERVERS = eINSTANCE.getSystem_Servers();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ServerImpl <em>Server</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ServerImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getServer()
     * @generated
     */
    EClass SERVER = eINSTANCE.getServer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__NAME = eINSTANCE.getServer_Name();

    /**
     * The meta object literal for the '<em><b>Conn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__CONN = eINSTANCE.getServer_Conn();

    /**
     * The meta object literal for the '<em><b>Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__EXPS = eINSTANCE.getServer_Exps();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ConnectionImpl <em>Connection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ConnectionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getConnection()
     * @generated
     */
    EClass CONNECTION = eINSTANCE.getConnection();

    /**
     * The meta object literal for the '<em><b>Ip Adr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION__IP_ADR = eINSTANCE.getConnection_IpAdr();

    /**
     * The meta object literal for the '<em><b>Website</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION__WEBSITE = eINSTANCE.getConnection_Website();

    /**
     * The meta object literal for the '<em><b>Portnumber</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION__PORTNUMBER = eINSTANCE.getConnection_Portnumber();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.BoardImpl <em>Board</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.BoardImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getBoard()
     * @generated
     */
    EClass BOARD = eINSTANCE.getBoard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOARD__NAME = eINSTANCE.getBoard_Name();

    /**
     * The meta object literal for the '<em><b>Board Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOARD__BOARD_MEMBERS = eINSTANCE.getBoard_BoardMembers();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.BoardMemberImpl <em>Board Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.BoardMemberImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getBoardMember()
     * @generated
     */
    EClass BOARD_MEMBER = eINSTANCE.getBoardMember();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ConditionalActionImpl <em>Conditional Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ConditionalActionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getConditionalAction()
     * @generated
     */
    EClass CONDITIONAL_ACTION = eINSTANCE.getConditionalAction();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ExpMemberImpl <em>Exp Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ExpMemberImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getExpMember()
     * @generated
     */
    EClass EXP_MEMBER = eINSTANCE.getExpMember();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.SensorImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Sensor Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__SENSOR_TYPES = eINSTANCE.getSensor_SensorTypes();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ActuatorImpl <em>Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ActuatorImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getActuator()
     * @generated
     */
    EClass ACTUATOR = eINSTANCE.getActuator();

    /**
     * The meta object literal for the '<em><b>Actuator Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR__ACTUATOR_TYPES = eINSTANCE.getActuator_ActuatorTypes();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ActuatorTypeImpl <em>Actuator Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ActuatorTypeImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getActuatorType()
     * @generated
     */
    EClass ACTUATOR_TYPE = eINSTANCE.getActuatorType();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR_TYPE__TYPE_NAME = eINSTANCE.getActuatorType_TypeName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR_TYPE__NAME = eINSTANCE.getActuatorType_Name();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR_TYPE__PINS = eINSTANCE.getActuatorType_Pins();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.SensorTypeImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getSensorType()
     * @generated
     */
    EClass SENSOR_TYPE = eINSTANCE.getSensorType();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_TYPE__TYPE_NAME = eINSTANCE.getSensorType_TypeName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_TYPE__NAME = eINSTANCE.getSensorType_Name();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_TYPE__PINS = eINSTANCE.getSensorType_Pins();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.PinImpl <em>Pin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.PinImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getPin()
     * @generated
     */
    EClass PIN = eINSTANCE.getPin();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIN__POWER = eINSTANCE.getPin_Power();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIN__INPUT = eINSTANCE.getPin_Input();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ConditionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Exp Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__EXP_MEMBERS = eINSTANCE.getCondition_ExpMembers();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.LogicExpImpl <em>Logic Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.LogicExpImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getLogicExp()
     * @generated
     */
    EClass LOGIC_EXP = eINSTANCE.getLogicExp();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXP__CONDITION = eINSTANCE.getLogicExp_Condition();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.BooleanImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__VALUE = eINSTANCE.getBoolean_Value();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ComparisonExpImpl <em>Comparison Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ComparisonExpImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getComparisonExp()
     * @generated
     */
    EClass COMPARISON_EXP = eINSTANCE.getComparisonExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON_EXP__LEFT = eINSTANCE.getComparisonExp_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON_EXP__OP = eINSTANCE.getComparisonExp_Op();

    /**
     * The meta object literal for the '<em><b>Rigth</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON_EXP__RIGTH = eINSTANCE.getComparisonExp_Rigth();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ExpressionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.FunctionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Board</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__BOARD = eINSTANCE.getFunction_Board();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ActuatorFunctionImpl <em>Actuator Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ActuatorFunctionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getActuatorFunction()
     * @generated
     */
    EClass ACTUATOR_FUNCTION = eINSTANCE.getActuatorFunction();

    /**
     * The meta object literal for the '<em><b>Actuator Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR_FUNCTION__ACTUATOR_TYPE = eINSTANCE.getActuatorFunction_ActuatorType();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.SensorFunctionImpl <em>Sensor Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.SensorFunctionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getSensorFunction()
     * @generated
     */
    EClass SENSOR_FUNCTION = eINSTANCE.getSensorFunction();

    /**
     * The meta object literal for the '<em><b>Sensor Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_FUNCTION__SENSOR_TYPE = eINSTANCE.getSensorFunction_SensorType();

  }

} //PycomPackage
