/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtext.pycom.PycomPackage#getSensorType()
 * @model
 * @generated
 */
public interface SensorType extends ModuleType
{
} // SensorType
