/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Sensor#getSensorTypes <em>Sensor Types</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends BoardMember
{
  /**
   * Returns the value of the '<em><b>Sensor Types</b></em>' containment reference list.
   * The list contents are of type {@link xtext.pycom.SensorType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor Types</em>' containment reference list.
   * @see xtext.pycom.PycomPackage#getSensor_SensorTypes()
   * @model containment="true"
   * @generated
   */
  EList<SensorType> getSensorTypes();

} // Sensor
