/**
 * generated by Xtext 2.17.0
 */
package xtext.pycom;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.SensorFunction#getSensorType <em>Sensor Type</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getSensorFunction()
 * @model
 * @generated
 */
public interface SensorFunction extends Function
{
  /**
   * Returns the value of the '<em><b>Sensor Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor Type</em>' reference.
   * @see #setSensorType(SensorType)
   * @see xtext.pycom.PycomPackage#getSensorFunction_SensorType()
   * @model
   * @generated
   */
  SensorType getSensorType();

  /**
   * Sets the value of the '{@link xtext.pycom.SensorFunction#getSensorType <em>Sensor Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor Type</em>' reference.
   * @see #getSensorType()
   * @generated
   */
  void setSensorType(SensorType value);

} // SensorFunction
