/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Server</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Server#getName <em>Name</em>}</li>
 *   <li>{@link xtext.pycom.Server#getConn <em>Conn</em>}</li>
 *   <li>{@link xtext.pycom.Server#getExps <em>Exps</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getServer()
 * @model
 * @generated
 */
public interface Server extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xtext.pycom.PycomPackage#getServer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xtext.pycom.Server#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Conn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conn</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conn</em>' containment reference.
   * @see #setConn(Connection)
   * @see xtext.pycom.PycomPackage#getServer_Conn()
   * @model containment="true"
   * @generated
   */
  Connection getConn();

  /**
   * Sets the value of the '{@link xtext.pycom.Server#getConn <em>Conn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conn</em>' containment reference.
   * @see #getConn()
   * @generated
   */
  void setConn(Connection value);

  /**
   * Returns the value of the '<em><b>Exps</b></em>' containment reference list.
   * The list contents are of type {@link xtext.pycom.ConditionalAction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exps</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exps</em>' containment reference list.
   * @see xtext.pycom.PycomPackage#getServer_Exps()
   * @model containment="true"
   * @generated
   */
  EList<ConditionalAction> getExps();

} // Server
