/*
 * generated by Xtext 2.16.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtext.pycom.ui.internal.PycomActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PycomExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PycomActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PycomActivator activator = PycomActivator.getInstance();
		return activator != null ? activator.getInjector(PycomActivator.XTEXT_PYCOM) : null;
	}

}
